package makaza.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import makaza.model.Roles;

@Mapper
public interface RolesMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table roles
	 * 
	 * @mbg.generated
	 */
	int insert(Roles record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table roles
	 * 
	 * @mbg.generated
	 */
	int insertSelective(Roles record);

	/**
	 * Get all roles
	 * 
	 * @return list roles
	 */
	List<Roles> selectAll();

	/**
	 * Get role by Id
	 * 
	 * @param id ID
	 * @return role
	 */
	Roles selectById(int id);

	/**
	 * Update role
	 * 
	 * @param record role
	 * @return quantity has been updated
	 */
	int update(Roles record);

	/**
	 * Delete role
	 * 
	 * @param record role
	 * @return quantity has been deleted
	 */
	int deleteLogic(int id, String delFlg);
}