package makaza.mapper;

import org.apache.ibatis.annotations.Mapper;

import makaza.model.UserRole;

@Mapper
public interface UserRoleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table user_role
	 * 
	 * @mbg.generated
	 */
	int insert(UserRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table user_role
	 * 
	 * @mbg.generated
	 */
	int insertSelective(UserRole record);

	/**
	 * Update userRole
	 * 
	 * @param record userRole
	 * @return quantity
	 */
	int update(UserRole record);
}