package makaza.model;

/**
 * Roles
 * @author Minh
 */
public class Roles {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column roles.ID
	 * 
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column roles.ROLE_NAME
	 * 
	 * @mbg.generated
	 */
	private String roleName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column roles.DEL_FLG
	 * 
	 * @mbg.generated
	 */
	private String delFlg;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column roles.ID
	 * 
	 * @return the value of roles.ID
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column roles.ID
	 * 
	 * @param id the value for roles.ID
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column roles.ROLE_NAME
	 * 
	 * @return the value of roles.ROLE_NAME
	 * @mbg.generated
	 */
	public String getRoleName() {
		return roleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column roles.ROLE_NAME
	 * 
	 * @param roleName the value for roles.ROLE_NAME
	 * @mbg.generated
	 */
	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column roles.ROLE_NAME
	 * 
	 * @return the value of roles.DEL_FLG
	 * @mbg.generated
	 */
	public String getDelFlg() {
		return delFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column roles.ROLE_NAME
	 * 
	 * @param roleName the value for roles.DEL_FLG
	 * @mbg.generated
	 */
	public void setDelFlg(String delFlg) {
		this.delFlg = delFlg;
	}
}