package makaza.model;

import java.util.Date;

/**
 * UserAccount
 * @author Minh
 */
public class UserAccount {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user_account.USER_NAME
	 * 
	 * @mbg.generated
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user_account.STATUS
	 * 
	 * @mbg.generated
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user_account.PASSWORD
	 * 
	 * @mbg.generated
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user_account.PASSWORD_REMINDER_TOKEN
	 * 
	 * @mbg.generated
	 */
	private String passwordReminderToken;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user_account.PASSWORD_REMINDER_EXPIRE
	 * 
	 * @mbg.generated
	 */
	private Date passwordReminderExpire;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user_account.EMAIL_CONFIRMATION_TOKEN
	 * 
	 * @mbg.generated
	 */
	private String emailConfirmationToken;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user_account.FIRST_NAME
	 * 
	 * @mbg.generated
	 */
	private String firstName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user_account.LAST_NAME
	 * 
	 * @mbg.generated
	 */
	private String lastName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user_account.EMAIL
	 * 
	 * @mbg.generated
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user_account.ADDRESS
	 * 
	 * @mbg.generated
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user_account.PHONE_NUMBER
	 * 
	 * @mbg.generated
	 */
	private String phoneNumber;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column roles.DEL_FLG
	 * 
	 * @mbg.generated
	 */
	private String delFlg;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user_account.USER_NAME
	 * 
	 * @return the value of user_account.USER_NAME
	 * @mbg.generated
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user_account.USER_NAME
	 * 
	 * @param userName the value for user_account.USER_NAME
	 * @mbg.generated
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user_account.STATUS
	 * 
	 * @return the value of user_account.STATUS
	 * @mbg.generated
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user_account.STATUS
	 * 
	 * @param status the value for user_account.STATUS
	 * @mbg.generated
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user_account.PASSWORD
	 * 
	 * @return the value of user_account.PASSWORD
	 * @mbg.generated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user_account.PASSWORD
	 * 
	 * @param password the value for user_account.PASSWORD
	 * @mbg.generated
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user_account.PASSWORD_REMINDER_TOKEN
	 * 
	 * @return the value of user_account.PASSWORD_REMINDER_TOKEN
	 * @mbg.generated
	 */
	public String getPasswordReminderToken() {
		return passwordReminderToken;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user_account.PASSWORD_REMINDER_TOKEN
	 * 
	 * @param passwordReminderToken the value for
	 *                              user_account.PASSWORD_REMINDER_TOKEN
	 * @mbg.generated
	 */
	public void setPasswordReminderToken(String passwordReminderToken) {
		this.passwordReminderToken = passwordReminderToken;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user_account.PASSWORD_REMINDER_EXPIRE
	 * 
	 * @return the value of user_account.PASSWORD_REMINDER_EXPIRE
	 * @mbg.generated
	 */
	public Date getPasswordReminderExpire() {
		return passwordReminderExpire;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user_account.PASSWORD_REMINDER_EXPIRE
	 * 
	 * @param passwordReminderExpire the value for
	 *                               user_account.PASSWORD_REMINDER_EXPIRE
	 * @mbg.generated
	 */
	public void setPasswordReminderExpire(Date passwordReminderExpire) {
		this.passwordReminderExpire = passwordReminderExpire;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user_account.EMAIL_CONFIRMATION_TOKEN
	 * 
	 * @return the value of user_account.EMAIL_CONFIRMATION_TOKEN
	 * @mbg.generated
	 */
	public String getEmailConfirmationToken() {
		return emailConfirmationToken;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user_account.EMAIL_CONFIRMATION_TOKEN
	 * 
	 * @param emailConfirmationToken the value for
	 *                               user_account.EMAIL_CONFIRMATION_TOKEN
	 * @mbg.generated
	 */
	public void setEmailConfirmationToken(String emailConfirmationToken) {
		this.emailConfirmationToken = emailConfirmationToken;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user_account.FIRST_NAME
	 * 
	 * @return the value of user_account.FIRST_NAME
	 * @mbg.generated
	 */
	public String getFirstName() {
		return firstName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user_account.FIRST_NAME
	 * 
	 * @param firstName the value for user_account.FIRST_NAME
	 * @mbg.generated
	 */
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user_account.LAST_NAME
	 * 
	 * @return the value of user_account.LAST_NAME
	 * @mbg.generated
	 */
	public String getLastName() {
		return lastName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user_account.LAST_NAME
	 * 
	 * @param lastName the value for user_account.LAST_NAME
	 * @mbg.generated
	 */
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user_account.EMAIL
	 * 
	 * @return the value of user_account.EMAIL
	 * @mbg.generated
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user_account.EMAIL
	 * 
	 * @param email the value for user_account.EMAIL
	 * @mbg.generated
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user_account.ADDRESS
	 * 
	 * @return the value of user_account.ADDRESS
	 * @mbg.generated
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user_account.ADDRESS
	 * 
	 * @param address the value for user_account.ADDRESS
	 * @mbg.generated
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user_account.PHONE_NUMBER
	 * 
	 * @return the value of user_account.PHONE_NUMBER
	 * @mbg.generated
	 */
	public String getPhoneNumber() {
		return phoneNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user_account.PHONE_NUMBER
	 * 
	 * @param phoneNumber the value for user_account.PHONE_NUMBER
	 * @mbg.generated
	 */
	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column roles.ROLE_NAME
	 * 
	 * @return the value of roles.DEL_FLG
	 * @mbg.generated
	 */
	public String getDelFlg() {
		return delFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column roles.ROLE_NAME
	 * 
	 * @param roleName the value for roles.DEL_FLG
	 * @mbg.generated
	 */
	public void setDelFlg(String delFlg) {
		this.delFlg = delFlg;
	}
}