package makaza.model;

/**
 * UserRole
 * @author Minh
 */
public class UserRole {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_role.USER_NAME
	 * @mbg.generated
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_role.ROLE_ID
	 * @mbg.generated
	 */
	private Integer roleId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_role.USER_NAME
	 * @return  the value of user_role.USER_NAME
	 * @mbg.generated
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_role.USER_NAME
	 * @param userName  the value for user_role.USER_NAME
	 * @mbg.generated
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_role.ROLE_ID
	 * @return  the value of user_role.ROLE_ID
	 * @mbg.generated
	 */
	public Integer getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_role.ROLE_ID
	 * @param roleId  the value for user_role.ROLE_ID
	 * @mbg.generated
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}
}